title: "root💀muzec-sec:~#"
#description: "Try Harder!!!"

show_downloads: false
show_repo: false

theme: jekyll-theme-hacker

github:
  is_project_page: false


plugins:
  - jekyll-sitemap

socialIcons:
  - name: X
    url: "https://X.com/muzecsec"

  - name: github
    url: "https://github.com/Muzec0318"

  - name: discord
    url: "Muzec"
